#TODO: need to retune all values
#TEST PLAN: 
#start all values at 0 and slowly increase P, then D, and if needed, I (mainly on heave)

yaw_angle_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 2.0 #roughly: 90 degrees error -> 180 degrees / second rate target
    kD: 0.0
    bias: 0.0
pitch_angle_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.5 
    kD: 0.0
    bias: 0.0
roll_angle_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.5
    kD: 0.0
    bias: 0.0
yaw_rate_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 0.45 #roughly: 90 degrees / second error -> 45% throttle  
    kD: 0.12
    bias: 0.0
pitch_rate_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 2.0
    kD: 0.7
    bias: 0.0
roll_rate_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 1.5
    kD: 0.32
    bias: 0.0
surge_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 70.0
    kD: 0.0
    bias: 0.0
sway_pid_controller:
  ros__parameters:
    kI: 0.0
    kP: 90.0
    kD: 0.0
    bias: 0.0
heave_pid_controller:
  ros__parameters:
    kI: 7.0
    kP: 100.0
    kD: 1.0
    bias: 0.0
    saturation_limit: 25.0
    decay: 1.0
x_translation_pid_controller:
  ros__parameters:
    kI: 0.1
    kP: 1.5
    kD: 0.0
    bias: 0.0
    max: 1.5
y_translation_pid_controller:
  ros__parameters:
    kI: 0.1
    kP: 1.5
    kD: 0.0
    bias: 0.0
    max: 1.5
z_translation_pid_controller:
  ros__parameters:
    kI: 0.1
    kP: 2.0
    kD: 0.0
    bias: 0.0
    max: 0.5
