onnx_segmentation_detector:
  ros__parameters:
    conf_threshold: 0.7
    mask_threshold: 0.7
    providers:
      #- TensorrtExecutionProvider
      - CUDAExecutionProvider
      #- CPUExecutionProvider
