esp32_bridge:
  ros__parameters:
    serial_port: '/dev/ttyUSB0'
    baud_rate: 115200
    killswitch_address: 66
    killswitch_index: 0
    mission_button_address: 66
    mission_button_index: 1
    mission_button_arm_time_ms: 5000
    battery_voltage_address: [100] #dummy value - invalid address
    battery_voltage_index: [2, 3, 4, 5]
    battery_voltage_read_mult: [1.0, 3.2222, 5.4444, 5.4444]
    motor_count: 8
    leak_sensor_addresses: [66, 67, 69]
    leak_sensor_indicies: [1, 1, 1]
    leak_sensor_threshold: 800.0
    max_throttle: 1800.0
    min_throttle: 1200.0
    motor_index_remapping: [1, 4, 7, 3, 5, 0, 2, 6]
