pose_control_layer:
    ros__parameters:
        update_frequency: 200.0
        x_angular.p_gain: 0.5
        x_linear.p_gain: 1.0
        x_linear.u_max: 0.6
        x_linear.u_min: -0.6
        y_angular.p_gain: 1.0
        y_linear.p_gain: 1.0
        y_linear.u_max: 1.0
        y_linear.u_min: -1.0
        z_angular.p_gain: 0.5
        z_linear.p_gain: 1.0
        z_linear.u_max: 1.0
        z_linear.u_min: -1.0
