velocity_control_layer:
  ros__parameters:
    update_frequency: 200.0
    x_angular.p_gain: 1.0
    x_linear.p_gain: 1.0
    y_angular.p_gain: 0.5
    y_linear.p_gain: 1.0
    z_angular.p_gain: 0.2
    z_linear.p_gain: 1.0
    
