float64[8] throttle
# throttle[0] = fli (front left inner motor)
# throttle[1] = fri (front right inner motor)
# throttle[2] = bli (back left inner motor)
# throttle[3] = bri (back right inner motor)
# throttle[4] = flo (front left outer motor)
# throttle[5] = fro (front right outer motor)
# throttle[6] = blo (back left outer motor)
# throttle[7] = bro (back right outer motor)
std_msgs/Header header
