accel_control_layer:
    ros__parameters:
        update_frequency: 50.0
        kbuoyancy: 0.17
        kdrag_x: 1.0
        kdrag_y: 3.0
        kdrag_yaw: 0.0
        kdrag_z: 0.0
        kmass_pitch: 0.13
        kmass_roll: 0.1
        kmass_x: 5.0
        kmass_y: 8.0
        kmass_yaw: 0.2
        kmass_z: 5.0
