pose_control_layer:
  ros__parameters:
    update_frequency: 100.0
    x_angular.p_gain: 0.5
    x_linear.p_gain: 0.0
    
    y_angular.p_gain: 2.0
    y_angular.d_gain: 0.1

    y_linear.p_gain: 0.0

    z_angular.p_gain: 0.0

    z_linear.p_gain: 1.0
    z_linear.u_max: 0.5 #max 0.5m/s setpoint
    z_linear.u_min: -0.5
    z_linear.clamp_values: true
