accel_control_layer:
    ros__parameters:
        update_frequency: 50.0
        kbuoyancy: 0.17
        kdrag_x: 0.0
        kdrag_y: 0.0
        kdrag_yaw: 0.0
        kdrag_z: 0.0
        kmass_pitch: 0.1
        kmass_roll: 0.1
        kmass_x: 5.0
        kmass_y: 5.0
        kmass_yaw: 0.1
        kmass_z: 5.0
